# Generated by Django 3.2.6 on 2024-02-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediSyncApp', '0002_auto_20240206_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
